language: generic

matrix:
  include:
    - os: linux
      python: 3.5
      env:
        - PYTHON_VERSION=3.5
        - MINICONDA_URL=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - os: linux
      python: 3.6
      env:
        - PYTHON_VERSION=3.6
        - MINICONDA_URL=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - os: osx
      python: 3.5
      env:
        - PYTHON_VERSION=3.5
        - MINICONDA_URL=https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        # - DYLD_LIBRARY_PATH=$HOME/miniconda/envs/pz/lib/python3.5/site-packages/protozfitsreader
    - os: osx
      python: 3.6
      env:
        - PYTHON_VERSION=3.6
        - MINICONDA_URL=https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        # - DYLD_LIBRARY_PATH=$HOME/miniconda/envs/pz/lib/python3.6/site-packages/protozfitsreader

install:
  - wget $MINICONDA_URL -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n pz python=$PYTHON_VERSION pip numpy protobuf # pytest
  - source activate pz
  - pip install -r requirements.txt
  - pip install pytest

script:
  - pytest -vv
